name: gohash_mobile_app
description: go-hash mobile app for Android and iOS.

dependencies:
  flutter:
    sdk: flutter

  gohash_mobile: ^0.0.1
  path_provider: ^0.4.0
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/gohash_db
